version: 0.0
os: linux
# 폴더경로는 원하는 곳에 하시면 됩니다. 꼭  /usr/share/nginx/html/안에 들어가지 않아도 됩니다.
files:
  - source: /
    destination: /home/ubuntu/dist.zip
    overwrite: yes
permissions:
  - object: /home/ubuntu/dist.zip
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: scripts/after.sh
      timeout: 180
      runas: ubuntu
